<?php

namespace ContainerSKILRsg;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArticleCoucheDemandeControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\ArticleCoucheDemandeController' shared autowired service.
     *
     * @return \App\Controller\ArticleCoucheDemandeController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\ArticleCoucheByCommandeController'] = $instance = new \App\Controller\ArticleCoucheByCommandeController(($container->privates['App\\Repository\\ArticleCoucheRepository'] ?? $container->load('getArticleCoucheRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\Controller\\ArticleCoucheByCommandeController', $container));

        return $instance;
    }
}
