<?php

namespace ContainerSKILRsg;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArticleCoucheByDemandeControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\ArticleCoucheByDemandeController' shared autowired service.
     *
     * @return \App\Controller\ArticleCoucheByDemandeController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\ArticleCoucheByDemandeController'] = $instance = new \App\Controller\ArticleCoucheByDemandeController(($container->privates['App\\Repository\\ArticlesRepository'] ?? $container->load('getArticlesRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\Controller\\ArticleCoucheByDemandeController', $container));

        return $instance;
    }
}
