<?php

namespace ContainerSKILRsg;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArgumentResolver_ServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'argument_resolver.service' shared service.
     *
     * @return \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\ArticleCoucheDemandeController::__invoke' => ['privates', '.service_locator.GL345QQ.App\\Controller\\ArticleCoucheDemandeController::__invoke()', 'getArticleCoucheDemandeControllerInvokeService', true],
            'App\\Controller\\ConsommationSemaineController::__invoke' => ['privates', '.service_locator.GL345QQ.App\\Controller\\ConsommationSemaineController::__invoke()', 'getConsommationSemaineControllerInvokeService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\ArticleCoucheDemandeController:__invoke' => ['privates', '.service_locator.GL345QQ.App\\Controller\\ArticleCoucheDemandeController::__invoke()', 'getArticleCoucheDemandeControllerInvokeService', true],
            'App\\Controller\\ArticleCoucheDemandeController' => ['privates', '.service_locator.GL345QQ.App\\Controller\\ArticleCoucheDemandeController::__invoke()', 'getArticleCoucheDemandeControllerInvokeService', true],
            'App\\Controller\\ConsommationSemaineController:__invoke' => ['privates', '.service_locator.GL345QQ.App\\Controller\\ConsommationSemaineController::__invoke()', 'getConsommationSemaineControllerInvokeService', true],
            'App\\Controller\\ConsommationSemaineController' => ['privates', '.service_locator.GL345QQ.App\\Controller\\ConsommationSemaineController::__invoke()', 'getConsommationSemaineControllerInvokeService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\ArticleCoucheDemandeController::__invoke' => '?',
            'App\\Controller\\ConsommationSemaineController::__invoke' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\ArticleCoucheDemandeController:__invoke' => '?',
            'App\\Controller\\ArticleCoucheDemandeController' => '?',
            'App\\Controller\\ConsommationSemaineController:__invoke' => '?',
            'App\\Controller\\ConsommationSemaineController' => '?',
        ]));
    }
}
