<?php

namespace ContainerSKILRsg;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConsommationSemaineControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\ConsommationSemaineController' shared autowired service.
     *
     * @return \App\Controller\ConsommationSemaineController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\ConsommationSemaineController'] = $instance = new \App\Controller\ConsommationSemaineController(($container->privates['App\\Repository\\ConsommationsRepository'] ?? $container->load('getConsommationsRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\Controller\\ConsommationSemaineController', $container));

        return $instance;
    }
}
