<?php

namespace ContainerSKILRsg;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommandeAffairesSystemesProviderService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\State\CommandeAffairesSystemesProvider' shared autowired service.
     *
     * @return \App\State\CommandeAffairesSystemesProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\State\\CommandeAffairesSystemesProvider'] = new \App\State\CommandeAffairesSystemesProvider(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));
    }
}
