<?php

namespace ContainerSKILRsg;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGrenaillageRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\GrenaillageRepository' shared autowired service.
     *
     * @return \App\Repository\GrenaillageRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\GrenaillageRepository'] = new \App\Repository\GrenaillageRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
