<?php

namespace ContainerSKILRsg;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOFsProcessorService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Processors\OFsProcessor' shared autowired service.
     *
     * @return \App\Processors\OFsProcessor
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Processors\\OFsProcessor'] = new \App\Processors\OFsProcessor(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['api_platform.doctrine.orm.state.persist_processor'] ?? $container->load('getApiPlatform_Doctrine_Orm_State_PersistProcessorService')));
    }
}
