<?php

namespace ContainerSKILRsg;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSemainesProcessorService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Processors\SemainesProcessor' shared autowired service.
     *
     * @return \App\Processors\SemainesProcessor
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Processors\\SemainesProcessor'] = new \App\Processors\SemainesProcessor(($container->privates['api_platform.doctrine.orm.state.persist_processor'] ?? $container->load('getApiPlatform_Doctrine_Orm_State_PersistProcessorService')));
    }
}
