<?php

namespace ContainerSKILRsg;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSemaineFilterService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Filter\SemaineFilter' shared autowired service.
     *
     * @return \App\Filter\SemaineFilter
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Filter\\SemaineFilter'] = new \App\Filter\SemaineFilter(($container->services['doctrine'] ?? self::getDoctrineService($container)), ($container->privates['logger'] ?? self::getLoggerService($container)));
    }
}
