<?php

namespace ContainerSKILRsg;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSurfaceCouchesRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\SurfaceCouchesRepository' shared autowired service.
     *
     * @return \App\Repository\SurfaceCouchesRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\SurfaceCouchesRepository'] = new \App\Repository\SurfaceCouchesRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
