api_platform:
    title: Hello API Platform
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    enable_entrypoint: true
    enable_docs: true
    mapping:
        paths:
        - '%kernel.project_dir%/src/Entity'