
services:
###> doctrine/doctrine-bundle ###
  database:
        image: mariadb
        restart: always
        environment:
          MARIADB_ROOT_PASSWORD: root
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
###> doctrine/doctrine-bundle ###
###< doctrine/doctrine-bundle ###
