<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Systemes extends \App\Entity\Systemes implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'Couches_syteme' => [parent::class, 'Couches_syteme', null],
        "\0".parent::class."\0".'commande_systeme' => [parent::class, 'commande_systeme', null],
        "\0".parent::class."\0".'fournisseur_systeme' => [parent::class, 'fournisseur_systeme', null],
        "\0".parent::class."\0".'grenaillage_systeme' => [parent::class, 'grenaillage_systeme', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'nom_systeme' => [parent::class, 'nom_systeme', null],
        "\0".parent::class."\0".'regieFP_Systeme' => [parent::class, 'regieFP_Systeme', null],
        "\0".parent::class."\0".'regieSFP_systeme' => [parent::class, 'regieSFP_systeme', null],
        "\0".parent::class."\0".'type_systeme' => [parent::class, 'type_systeme', null],
        'Couches_syteme' => [parent::class, 'Couches_syteme', null],
        'commande_systeme' => [parent::class, 'commande_systeme', null],
        'fournisseur_systeme' => [parent::class, 'fournisseur_systeme', null],
        'grenaillage_systeme' => [parent::class, 'grenaillage_systeme', null],
        'id' => [parent::class, 'id', null],
        'nom_systeme' => [parent::class, 'nom_systeme', null],
        'regieFP_Systeme' => [parent::class, 'regieFP_Systeme', null],
        'regieSFP_systeme' => [parent::class, 'regieSFP_systeme', null],
        'type_systeme' => [parent::class, 'type_systeme', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
