<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Commandes extends \App\Entity\Commandes implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'affaire_commande' => [parent::class, 'affaire_commande', null],
        "\0".parent::class."\0".'articleCouches_commande' => [parent::class, 'articleCouches_commande', null],
        "\0".parent::class."\0".'commentaire_commande' => [parent::class, 'commentaire_commande', null],
        "\0".parent::class."\0".'demandes_commande' => [parent::class, 'demandes_commande', null],
        "\0".parent::class."\0".'eureka_commande' => [parent::class, 'eureka_commande', null],
        "\0".parent::class."\0".'ficheH_commande' => [parent::class, 'ficheH_commande', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'pvPeinture_commande' => [parent::class, 'pvPeinture_commande', null],
        "\0".parent::class."\0".'surface_commande' => [parent::class, 'surface_commande', null],
        "\0".parent::class."\0".'systeme_commande' => [parent::class, 'systeme_commande', null],
        'affaire_commande' => [parent::class, 'affaire_commande', null],
        'articleCouches_commande' => [parent::class, 'articleCouches_commande', null],
        'commentaire_commande' => [parent::class, 'commentaire_commande', null],
        'demandes_commande' => [parent::class, 'demandes_commande', null],
        'eureka_commande' => [parent::class, 'eureka_commande', null],
        'ficheH_commande' => [parent::class, 'ficheH_commande', null],
        'id' => [parent::class, 'id', null],
        'pvPeinture_commande' => [parent::class, 'pvPeinture_commande', null],
        'surface_commande' => [parent::class, 'surface_commande', null],
        'systeme_commande' => [parent::class, 'systeme_commande', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
