<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class OFs extends \App\Entity\OFs implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'avancement_of' => [parent::class, 'avancement_of', null],
        "\0".parent::class."\0".'cabine_of' => [parent::class, 'cabine_of', null],
        "\0".parent::class."\0".'consommations_of' => [parent::class, 'consommations_of', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'idDemande_of' => [parent::class, 'idDemande_of', null],
        "\0".parent::class."\0".'jour_of' => [parent::class, 'jour_of', null],
        "\0".parent::class."\0".'semaine_of' => [parent::class, 'semaine_of', null],
        'avancement_of' => [parent::class, 'avancement_of', null],
        'cabine_of' => [parent::class, 'cabine_of', null],
        'consommations_of' => [parent::class, 'consommations_of', null],
        'id' => [parent::class, 'id', null],
        'idDemande_of' => [parent::class, 'idDemande_of', null],
        'jour_of' => [parent::class, 'jour_of', null],
        'semaine_of' => [parent::class, 'semaine_of', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
