<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Semaines extends \App\Entity\Semaines implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'annees' => [parent::class, 'annees', null],
        "\0".parent::class."\0".'dateDebut_semaine' => [parent::class, 'dateDebut_semaine', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'mois' => [parent::class, 'mois', null],
        "\0".parent::class."\0".'ofs_semaine' => [parent::class, 'ofs_semaine', null],
        "\0".parent::class."\0".'semaine' => [parent::class, 'semaine', null],
        'annees' => [parent::class, 'annees', null],
        'dateDebut_semaine' => [parent::class, 'dateDebut_semaine', null],
        'id' => [parent::class, 'id', null],
        'mois' => [parent::class, 'mois', null],
        'ofs_semaine' => [parent::class, 'ofs_semaine', null],
        'semaine' => [parent::class, 'semaine', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
