<?php

namespace ContainerIxNiiDR;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConsommationSemaineControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\ConsommationSemaineController' shared autowired service.
     *
     * @return \App\Controller\ConsommationSemaineController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'ConsommationSemaineController.php';

        $container->services['App\\Controller\\ConsommationSemaineController'] = $instance = new \App\Controller\ConsommationSemaineController(($container->privates['App\\Repository\\ConsommationsRepository'] ?? $container->load('getConsommationsRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\Controller\\ConsommationSemaineController', $container));

        return $instance;
    }
}
