<?php

namespace ContainerIxNiiDR;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommandeAffairesSystemesProviderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\State\CommandeAffairesSystemesProvider' shared autowired service.
     *
     * @return \App\State\CommandeAffairesSystemesProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'State'.\DIRECTORY_SEPARATOR.'CommandeAffairesSystemesProvider.php';

        return $container->privates['App\\State\\CommandeAffairesSystemesProvider'] = new \App\State\CommandeAffairesSystemesProvider(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));
    }
}
