<?php

namespace ContainerIxNiiDR;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSemainesProcessorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Processors\SemainesProcessor' shared autowired service.
     *
     * @return \App\Processors\SemainesProcessor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'api-platform'.\DIRECTORY_SEPARATOR.'state'.\DIRECTORY_SEPARATOR.'ProcessorInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Processors'.\DIRECTORY_SEPARATOR.'SemainesProcessor.php';

        return $container->privates['App\\Processors\\SemainesProcessor'] = new \App\Processors\SemainesProcessor(($container->privates['api_platform.doctrine.orm.state.persist_processor'] ?? $container->load('getApiPlatform_Doctrine_Orm_State_PersistProcessorService')));
    }
}
