<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerR8JqYrI\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerR8JqYrI/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerR8JqYrI.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerR8JqYrI\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerR8JqYrI\App_KernelDevDebugContainer([
    'container.build_hash' => 'R8JqYrI',
    'container.build_id' => '6a3b83ac',
    'container.build_time' => 1739891316,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerR8JqYrI');
