<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerI55UUYz\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerI55UUYz/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerI55UUYz.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerI55UUYz\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerI55UUYz\App_KernelDevDebugContainer([
    'container.build_hash' => 'I55UUYz',
    'container.build_id' => '292fdeef',
    'container.build_time' => 1740730461,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerI55UUYz');
