<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBy4yypr\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBy4yypr/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBy4yypr.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBy4yypr\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBy4yypr\App_KernelDevDebugContainer([
    'container.build_hash' => 'By4yypr',
    'container.build_id' => '3a3ff41f',
    'container.build_time' => 1740404126,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBy4yypr');
