<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Articles extends \App\Entity\Articles implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'articleCouches_article' => [parent::class, 'articleCouches_article', null],
        "\0".parent::class."\0".'consommation_article' => [parent::class, 'consommation_article', null],
        "\0".parent::class."\0".'designation_article' => [parent::class, 'designation_article', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        'articleCouches_article' => [parent::class, 'articleCouches_article', null],
        'consommation_article' => [parent::class, 'consommation_article', null],
        'designation_article' => [parent::class, 'designation_article', null],
        'id' => [parent::class, 'id', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
