<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Couches extends \App\Entity\Couches implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'articleCouches_couche' => [parent::class, 'articleCouches_couche', null],
        "\0".parent::class."\0".'epaisseur_couche' => [parent::class, 'epaisseur_couche', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'nom_couche' => [parent::class, 'nom_couche', null],
        "\0".parent::class."\0".'systeme_couche' => [parent::class, 'systeme_couche', null],
        "\0".parent::class."\0".'tarif_couche' => [parent::class, 'tarif_couche', null],
        'articleCouches_couche' => [parent::class, 'articleCouches_couche', null],
        'epaisseur_couche' => [parent::class, 'epaisseur_couche', null],
        'id' => [parent::class, 'id', null],
        'nom_couche' => [parent::class, 'nom_couche', null],
        'systeme_couche' => [parent::class, 'systeme_couche', null],
        'tarif_couche' => [parent::class, 'tarif_couche', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
