<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Demandes extends \App\Entity\Demandes implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'Of_demande' => [parent::class, 'Of_demande', null],
        "\0".parent::class."\0".'commande_demande' => [parent::class, 'commande_demande', null],
        "\0".parent::class."\0".'date_demande' => [parent::class, 'date_demande', null],
        "\0".parent::class."\0".'etat_demande' => [parent::class, 'etat_demande', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'nombrePiece_demande' => [parent::class, 'nombrePiece_demande', null],
        "\0".parent::class."\0".'numero_demande' => [parent::class, 'numero_demande', null],
        "\0".parent::class."\0".'surfaceCouches_demande' => [parent::class, 'surfaceCouches_demande', null],
        "\0".parent::class."\0".'surface_demande' => [parent::class, 'surface_demande', null],
        'Of_demande' => [parent::class, 'Of_demande', null],
        'commande_demande' => [parent::class, 'commande_demande', null],
        'date_demande' => [parent::class, 'date_demande', null],
        'etat_demande' => [parent::class, 'etat_demande', null],
        'id' => [parent::class, 'id', null],
        'nombrePiece_demande' => [parent::class, 'nombrePiece_demande', null],
        'numero_demande' => [parent::class, 'numero_demande', null],
        'surfaceCouches_demande' => [parent::class, 'surfaceCouches_demande', null],
        'surface_demande' => [parent::class, 'surface_demande', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
