<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ArticleCouche extends \App\Entity\ArticleCouche implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'articles_articleCouche' => [parent::class, 'articles_articleCouche', null],
        "\0".parent::class."\0".'commande_articleCouche' => [parent::class, 'commande_articleCouche', null],
        "\0".parent::class."\0".'couche_articleCouche' => [parent::class, 'couche_articleCouche', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'surfaceCouches_articleCouche' => [parent::class, 'surfaceCouches_articleCouche', null],
        "\0".parent::class."\0".'tarif_articleCouche' => [parent::class, 'tarif_articleCouche', null],
        'articles_articleCouche' => [parent::class, 'articles_articleCouche', null],
        'commande_articleCouche' => [parent::class, 'commande_articleCouche', null],
        'couche_articleCouche' => [parent::class, 'couche_articleCouche', null],
        'id' => [parent::class, 'id', null],
        'surfaceCouches_articleCouche' => [parent::class, 'surfaceCouches_articleCouche', null],
        'tarif_articleCouche' => [parent::class, 'tarif_articleCouche', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
