<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Grenaillage extends \App\Entity\Grenaillage implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'nom_grenaillage' => [parent::class, 'nom_grenaillage', null],
        "\0".parent::class."\0".'systemes_grenaillage' => [parent::class, 'systemes_grenaillage', null],
        "\0".parent::class."\0".'tarif_grenaillage' => [parent::class, 'tarif_grenaillage', null],
        "\0".parent::class."\0".'typeChantier_grenaillage' => [parent::class, 'typeChantier_grenaillage', null],
        'id' => [parent::class, 'id', null],
        'nom_grenaillage' => [parent::class, 'nom_grenaillage', null],
        'systemes_grenaillage' => [parent::class, 'systemes_grenaillage', null],
        'tarif_grenaillage' => [parent::class, 'tarif_grenaillage', null],
        'typeChantier_grenaillage' => [parent::class, 'typeChantier_grenaillage', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
